apiVersion: v1
kind: Secret
metadata:
  name: {{ include "example.fullname" . }}
  labels:
    {{- include "example.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.secrets.API_KEY | b64enc | quote }}
