name: ci

on: pull_request

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Scan image
      uses: anchore/scan-action@v3
      with:
        # hardcoded for example purpose, it should be scanning image created from the CI
        image: "nginxinc/nginx-unprivileged:1.20"
