apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "example.fullname" . }}
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
        {{- include "example.selectorLabels" . | nindent 6 }}

